name: Pull Request Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies (including optional)
        run: npm ci --include=optional

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Build (check)
        run: npm run build
        env:
          NODE_ENV: production
